### ISSUE TITLE
How to alt tab windows?

### ISSUE THREAD

**Issue by brightersun99** [rhaleblian/pirix#3]
title

**Comment by rhaleblian** [comment]
First thing would be to verify that this modern feature never got into mwm after the age of IRIX and HP-UX.
If no, look at this as a custom mwm add and custom build.
There has been some motivation for a custom build, to try to add the Toolchest, correct window borders, and an IRIX-like file manager.

**Comment by rhaleblian** [comment]
This is in mwm and possible to enable.  In `$HOME/.config/pirix/Xresources`, change line

    Mwm*keyboardFocusPolicy: pointer

to

    Mwm*keyboardFocusPolicy: explicit

and restart the desktop.

This will change window keyboard focus such that you have to click on the window now, and that is necessary for Alt-tab to work.

**Comment by rhaleblian** [comment]
The above change was made to the master branch.  Most people will want this.  Change the setting to `pointer` to get the older behaviour.
